// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lekcjaApi.DB;

#nullable disable

namespace lekcjaApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240926195807_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lekcjaApi.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Name = "kropka",
                            ShelterId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 5,
                            Name = "budyń",
                            ShelterId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            Name = "Robberto",
                            ShelterId = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 50,
                            Name = "Reksio",
                            ShelterId = 2
                        },
                        new
                        {
                            Id = 5,
                            Age = 51,
                            Name = "Scooby",
                            ShelterId = 2
                        },
                        new
                        {
                            Id = 6,
                            Age = 17,
                            Name = "kudłaty",
                            ShelterId = 2
                        });
                });

            modelBuilder.Entity("lekcjaApi.Entities.Shelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Panki,ulica kuchenna 3",
                            Name = "zooshelter"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "warszawa,ulica kresa 13",
                            Name = "kreskówkowe shronisko "
                        });
                });

            modelBuilder.Entity("lekcjaApi.Entities.Pet", b =>
                {
                    b.HasOne("lekcjaApi.Entities.Shelter", "Shelter")
                        .WithMany("Pets")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("lekcjaApi.Entities.Shelter", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
